name: Build/release

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [linux, win32, darwin]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: ./scripts/setup.sh

      - name: Install Node dependencies
        run: npm install

      - name: Build for ${{ matrix.platform }}
        run: npm run make -- --platform ${{ matrix.platform }}

        # with:
        #   github_token: ${{ secrets.github_token }}
        #   release: ${{ startsWith(github.ref, 'refs/tags/v') }}