name: Build/release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: ./scripts/setup.sh

      - name: Install Node dependencies
        run: npm install

      - name: Make (Linux)
        run: npm run make -- --platform linux

      - name: Make (Windows)
        run: npm run make -- --platform win32

      - name: Make (macOS)
        run: npm run make -- --platform darwin

      - name: Create a release for new tags
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            out/make/deb/x64/*.deb
            out/make/rpm/x64/*.rpm
            out/make/squirrel.windows/x64/*.exe
            out/make/zip/darwin/x64/*.zip
